name: fantasia
description: A new Flutter project.
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_route: ^2.2.0
  device_preview: ^0.7.4
  file_saver: ^0.0.10
  flutter:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_svg: ^0.22.0
  get_it: ^7.1.3
  google_fonts: ^2.1.0
  injectable: ^1.4.1
  logger: ^1.0.0
  screenshot: ^1.2.3
  stacked: ^2.1.7
  stacked_themes: ^0.3.6

dev_dependencies:
  auto_route_generator: ^2.1.0

  # Generators
  build_runner: ^2.0.4
  flutter_launcher_icons: ^0.9.0
  flutter_test:
    sdk: flutter

  # linting
  injectable_generator: ^1.4.1

flutter:
  uses-material-design: true
  # assets:
  # - assets/
  # fonts:
  # - family: Open Sans
  #   fonts:
  # - asset: assets/fonts/Open_Sans/OpenSans-Bold.ttf
  #   style: italic
